/* ==========================================================================
   Thali Trail — client-side Apriori recommendation app
   Loads precomputed products.json + rules.json (generated by
   generate_rules.py from the original notebook) and does everything
   else — selection, matching, rendering — in the browser. No backend.
   ========================================================================== */

(function () {
  "use strict";

  const state = {
    products: [],
    rules: [],
    itemsets: [],
    selected: new Set(),
    activeCategory: "All",
  };

  const els = {
    menuGrid: document.getElementById("menuGrid"),
    categoryChips: document.getElementById("categoryChips"),
    recoGrid: document.getElementById("recoGrid"),
    recoHint: document.getElementById("recoHint"),
    supportBars: document.getElementById("supportBars"),
    rulesTable: document.querySelector("#rulesTable tbody"),
    rulesPanel: document.getElementById("rulesPanel"),
    rulesToggle: document.getElementById("rulesToggle"),
    tray: document.getElementById("tray"),
    trayChips: document.getElementById("trayChips"),
    traySummaryText: document.getElementById("traySummaryText"),
    clearTray: document.getElementById("clearTray"),
  };

  init();

  async function init() {
    const [products, rules, itemsets] = await Promise.all([
      fetchJSON("data/products.json"),
      fetchJSON("data/rules.json"),
      fetchJSON("data/frequent_itemsets.json"),
    ]);

    state.products = products;
    state.rules = rules;
    state.itemsets = itemsets;

    renderCategoryChips();
    renderMenu();
    renderSupportBars();
    renderRulesTable();
    renderRecommendations();

    els.clearTray.addEventListener("click", () => {
      state.selected.clear();
      syncSelectionUI();
    });

    els.rulesToggle.addEventListener("click", () => {
      const isHidden = els.rulesPanel.hasAttribute("hidden");
      if (isHidden) {
        els.rulesPanel.removeAttribute("hidden");
        els.rulesToggle.setAttribute("aria-expanded", "true");
        els.rulesToggle.textContent = "Hide the rule engine";
        els.rulesPanel.scrollIntoView({ behavior: "smooth", block: "start" });
      } else {
        els.rulesPanel.setAttribute("hidden", "");
        els.rulesToggle.setAttribute("aria-expanded", "false");
        els.rulesToggle.textContent = "View the rule engine";
      }
    });
  }

  async function fetchJSON(path) {
    const res = await fetch(path);
    if (!res.ok) throw new Error(`Failed to load ${path}`);
    return res.json();
  }

  /* ---------------------------------------------------------------------
     Category filter chips
     --------------------------------------------------------------------- */
  function renderCategoryChips() {
    const categories = ["All", ...new Set(state.products.map((p) => p.category))];
    els.categoryChips.innerHTML = "";
    categories.forEach((cat) => {
      const btn = document.createElement("button");
      btn.className = "chip";
      btn.textContent = cat;
      btn.type = "button";
      btn.setAttribute("aria-pressed", String(cat === state.activeCategory));
      btn.addEventListener("click", () => {
        state.activeCategory = cat;
        [...els.categoryChips.children].forEach((c) =>
          c.setAttribute("aria-pressed", String(c === btn))
        );
        renderMenu();
      });
      els.categoryChips.appendChild(btn);
    });
  }

  /* ---------------------------------------------------------------------
     Menu grid
     --------------------------------------------------------------------- */
  function renderMenu() {
    const list =
      state.activeCategory === "All"
        ? state.products
        : state.products.filter((p) => p.category === state.activeCategory);

    els.menuGrid.innerHTML = "";
    list.forEach((product) => {
      els.menuGrid.appendChild(buildDishCard(product));
    });
  }

  function buildDishCard(product) {
    const card = document.createElement("button");
    card.type = "button";
    card.className = "dish-card";
    card.setAttribute("aria-pressed", String(state.selected.has(product.name)));
    card.dataset.name = product.name;

    card.innerHTML = `
      <div class="plate">
        ${buildImageMarkup(product, 96)}
        <span class="check" aria-hidden="true">&#10003;</span>
      </div>
      <div class="dish-meta">
        <span class="dish-name">${escapeHTML(product.name)}</span>
        <span class="dish-category">${escapeHTML(product.category)}</span>
        <p class="dish-desc">${escapeHTML(product.description)}</p>
        <div class="dish-foot">
          <span class="dish-price">₹${product.price}</span>
          <span class="dish-rating">★ ${product.rating.toFixed(1)}</span>
        </div>
      </div>
    `;

    card.addEventListener("click", () => toggleSelection(product.name));
    return card;
  }

  function buildImageMarkup(product, size) {
    const uid = `img-${product.id}-${Math.random().toString(36).slice(2, 7)}`;
    return `<img id="${uid}" src="${product.image}" alt="${escapeHTML(product.name)}"
              loading="lazy" width="${size}" height="${size}"
              onerror="window.__thaliImgFallback(this, '${product.fallbackImage}', '${escapeAttr(product.emoji)}')" />`;
  }

  // exposed globally so inline onerror handlers (fast, no re-render) can call it
  window.__thaliImgFallback = function (imgEl, fallbackSrc, emoji) {
    if (imgEl.dataset.stage === "fallback") {
      // fallback also failed — swap to emoji tile
      const span = document.createElement("span");
      span.className = "emoji-fallback";
      span.textContent = emoji;
      imgEl.replaceWith(span);
      return;
    }
    imgEl.dataset.stage = "fallback";
    imgEl.src = fallbackSrc;
  };

  /* ---------------------------------------------------------------------
     Selection + tray
     --------------------------------------------------------------------- */
  function toggleSelection(name) {
    if (state.selected.has(name)) {
      state.selected.delete(name);
    } else {
      state.selected.add(name);
    }
    syncSelectionUI();
  }

  function syncSelectionUI() {
    [...els.menuGrid.children].forEach((card) => {
      card.setAttribute("aria-pressed", String(state.selected.has(card.dataset.name)));
    });

    if (state.selected.size === 0) {
      els.tray.hidden = true;
    } else {
      els.tray.hidden = false;
      els.trayChips.innerHTML = "";
      state.selected.forEach((name) => {
        const chip = document.createElement("span");
        chip.className = "tray-chip";
        chip.innerHTML = `${escapeHTML(name)} <button type="button" aria-label="Remove ${escapeAttr(
          name
        )}">&times;</button>`;
        chip.querySelector("button").addEventListener("click", () => toggleSelection(name));
        els.trayChips.appendChild(chip);
      });
    }

    els.traySummaryText.textContent =
      state.selected.size === 0
        ? "No dishes selected yet"
        : `${state.selected.size} dish${state.selected.size > 1 ? "es" : ""} selected`;

    renderRecommendations();
  }

  /* ---------------------------------------------------------------------
     Recommendation engine — mirrors the notebook's recommend(item):
     a rule fires when every item in its antecedent set is in the
     current selection; its consequents (if not already selected)
     become candidates, ranked by confidence.
     --------------------------------------------------------------------- */
  function computeRecommendations() {
    if (state.selected.size === 0) return [];

    const best = new Map(); // consequent name -> { rule, because: Set }

    state.rules.forEach((rule) => {
      const antecedentsMet = rule.antecedents.every((a) => state.selected.has(a));
      if (!antecedentsMet) return;

      rule.consequents.forEach((cons) => {
        if (state.selected.has(cons)) return; // already ordered

        const existing = best.get(cons);
        if (!existing || rule.confidence > existing.rule.confidence) {
          best.set(cons, { rule, because: rule.antecedents });
        }
      });
    });

    return [...best.entries()]
      .map(([name, data]) => ({ name, ...data }))
      .sort((a, b) => b.rule.confidence - a.rule.confidence || b.rule.lift - a.rule.lift);
  }

  function renderRecommendations() {
    const recos = computeRecommendations();

    if (state.selected.size === 0) {
      els.recoHint.textContent =
        "Select a dish above — this fills in with what the algorithm recommends alongside it.";
      els.recoGrid.innerHTML = "";
      return;
    }

    if (recos.length === 0) {
      els.recoHint.textContent = `No confident pairing found for your current selection yet — try adding another dish.`;
      els.recoGrid.innerHTML = `<div class="reco-empty">No rule in the training data clears the 50% confidence bar for this combination.</div>`;
      return;
    }

    els.recoHint.textContent = `Based on ${state.selected.size} selected dish${
      state.selected.size > 1 ? "es" : ""
    }, ranked by confidence.`;

    els.recoGrid.innerHTML = "";
    recos.forEach((r) => {
      const product = state.products.find((p) => p.name === r.name);
      if (!product) return;

      const confPct = Math.round(r.rule.confidence * 100);
      const isTrending = r.rule.lift > 1.2;

      const card = document.createElement("div");
      card.className = "reco-card";
      card.innerHTML = `
        <div class="reco-thumb">${buildImageMarkup(product, 64)}</div>
        <div class="reco-body">
          <div class="reco-body-top">
            <span class="reco-name">${escapeHTML(product.name)}</span>
            <span class="dish-price">₹${product.price}</span>
          </div>
          <p class="reco-because">because you picked <b>${escapeHTML(
            r.because.join(" + ")
          )}</b>${isTrending ? '<span class="lift-badge">trending pair</span>' : ""}</p>
          <div class="trail" title="Confidence ${confPct}%">
            <div class="trail-fill" style="width:${confPct}%"></div>
          </div>
          <div class="reco-stats">
            <span>conf <b>${confPct}%</b></span>
            <span>support <b>${r.rule.support.toFixed(2)}</b></span>
            <span>lift <b>${r.rule.lift.toFixed(2)}</b></span>
          </div>
        </div>
        <button class="add-btn" type="button" aria-label="Add ${escapeAttr(product.name)}">+</button>
      `;
      card.querySelector(".add-btn").addEventListener("click", () => toggleSelection(product.name));
      els.recoGrid.appendChild(card);
    });
  }

  /* ---------------------------------------------------------------------
     Frequent itemsets bar chart
     --------------------------------------------------------------------- */
  function renderSupportBars() {
    const top = [...state.itemsets].sort((a, b) => b.support - a.support).slice(0, 10);
    const max = Math.max(...top.map((t) => t.support), 0.01);

    els.supportBars.innerHTML = "";
    top.forEach((t) => {
      const row = document.createElement("div");
      row.className = "bar-row";
      row.innerHTML = `
        <span class="bar-label">${escapeHTML(t.items.join(" + "))}</span>
        <span class="bar-track"><span class="bar-fill" style="width:${(t.support / max) * 100}%"></span></span>
        <span class="bar-value">${t.support.toFixed(2)}</span>
      `;
      els.supportBars.appendChild(row);
    });
  }

  /* ---------------------------------------------------------------------
     Full rules table
     --------------------------------------------------------------------- */
  function renderRulesTable() {
    els.rulesTable.innerHTML = "";
    state.rules.forEach((rule) => {
      const confPct = Math.round(rule.confidence * 100);
      const tr = document.createElement("tr");
      tr.innerHTML = `
        <td>${escapeHTML(rule.antecedents.join(" + "))}</td>
        <td>${escapeHTML(rule.consequents.join(" + "))}</td>
        <td>${rule.support.toFixed(2)}</td>
        <td class="conf-cell">
          <span class="trail"><span class="trail-fill" style="width:${confPct}%"></span></span>
          ${confPct}%
        </td>
        <td>${rule.lift.toFixed(2)}</td>
      `;
      els.rulesTable.appendChild(tr);
    });
  }

  /* ---------------------------------------------------------------------
     Utils
     --------------------------------------------------------------------- */
  function escapeHTML(str) {
    return String(str).replace(/[&<>"']/g, (c) => ({
      "&": "&amp;",
      "<": "&lt;",
      ">": "&gt;",
      '"': "&quot;",
      "'": "&#39;",
    }[c]));
  }
  function escapeAttr(str) {
    return escapeHTML(str).replace(/'/g, "&#39;");
  }
})();
